version: '3.8'

services:
  db:
    build: 
      context: .
      dockerfile: ./Docker/db/Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - datascience
  
  pg_admin:
    build: 
      context: .
      dockerfile: ./Docker/pg_admin/Dockerfile
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    networks:
      - datascience

networks:
  datascience:
    driver: bridge

volumes:
  db-data: